const list = [
  {
    id: 1,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-1.jpg',
    category: ['한인민박', '제주도'],
    title:
      '1[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐#독채 #자쿠지 #바베큐#독채 #자쿠지 #바베큐#독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 2,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-2.jpg',
    category: ['한인민박', '제주도'],
    title: '2[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 120000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 3,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-3.jpg',
    category: ['한인민박', '제주도'],
    title: '3[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 130000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 4,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-4.jpg',
    category: ['한인민박', '제주도'],
    title: '4[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 140000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 5,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-5.jpg',
    category: ['한인민박', '제주도'],
    title: '5[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 150000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 6,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-6.jpg',
    category: ['한인민박', '제주도'],
    title: '6[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 7,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-7.jpg',
    category: ['한인민박', '제주도'],
    title:
      '7[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐7[동쪽/펜션] 북촌리:멤버 ',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 8,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-8.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 9,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-9.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 10,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-10.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 11,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-11.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 12,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-12.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 13,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-13.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 14,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-14.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 15,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-15.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 16,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-16.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 17,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-17.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 18,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-18.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 19,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-19.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 20,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-20.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 21,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-21.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 22,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-22.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 23,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-23.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 24,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-24.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 25,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-25.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 26,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-26.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 27,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-27.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 28,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-28.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 29,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-29.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 30,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-30.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 31,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-31.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 32,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-32.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 33,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-33.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 34,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-34.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 35,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-35.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 36,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-36.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 37,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-37.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 38,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-38.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 39,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-39.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 40,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-40.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 41,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-41.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 42,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-42.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 43,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-43.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 44,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-44.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 45,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-45.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 46,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-46.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 47,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-47.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 48,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-48.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 49,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-49.jpg',
    category: ['한인민박', '제주도'],
    title: '[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 50,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-50.jpg',
    category: ['한인민박', '제주도'],
    title: '50[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 51,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-51.jpg',
    category: ['한인민박', '제주도'],
    title: '51[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 52,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-52.jpg',
    category: ['한인민박', '제주도'],
    title: '52[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 53,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-53.jpg',
    category: ['한인민박', '제주도'],
    title: '53[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 54,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-54.jpg',
    category: ['한인민박', '제주도'],
    title: '54[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
  {
    id: 55,
    img:
      'https://d2ur7st6jjikze.cloudfront.net/share/thumbnail/thumbnail-55.jpg',
    category: ['한인민박', '제주도'],
    title: '55[동쪽/펜션] 북촌리:멤버 #독채 #자쿠지 #바베큐',
    price: 110000,
    point: 3,
    reviews: 13,
    wish: false,
  },
];

export default list;
